version: '3.7'
services:
    rastahorn-web:
        build: rastahorn-web/
        container_name: rastahorn-web
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        volumes:
            - ./data/logs/nginx:/var/log/nginx
            - ./www:/var/www
        links:
            - rastahorn-php
    rastahorn-php:
        image: php:7-fpm
        volumes:
            - ./www:/var/www
networks:
    default:
        external:
            name: internal-network